"""initial migration

Revision ID: 0cb36e3c0285
Revises: 
Create Date: 2025-03-14 19:51:18.847274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cb36e3c0285'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('discord_user_id')
    )
    op.create_table('card_drop_events',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cards_dropped_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('started_by_user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['started_by_user_id'], ['users.discord_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_cards',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pokemon_tcg_card_id', sa.String(), nullable=False),
    sa.Column('pattern_number', sa.Integer(), nullable=False),
    sa.Column('float_value', sa.Float(), nullable=False),
    sa.Column('print_number', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('drop_event_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['drop_event_id'], ['card_drop_events.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.discord_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_cards')
    op.drop_table('card_drop_events')
    op.drop_table('users')
    # ### end Alembic commands ###
